#!/usr/bin/env python3

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))

from cryptocore.csprng import generate_random_bytes, generate_key

def test_key_uniqueness():
    key_set = set()
    num_keys = 1000
    
    print(f"Generating {num_keys} random keys...")
    
    for i in range(num_keys):
        key = generate_key(16)
        key_hex = key.hex()
        
        # Check for uniqueness
        if key_hex in key_set:
            raise AssertionError(f"Duplicate key found at iteration {i}: {key_hex}")
        key_set.add(key_hex)
        
        if (i + 1) % 100 == 0:
            print(f"  Generated {i + 1} unique keys...")
    
    print(f"Successfully generated {len(key_set)} unique keys.")

def test_entropy():
    print("Testing entropy of generated bytes...")
    
    total_bits = 0
    total_bytes = 0
    sample_size = 10000  # 10KB
    
    random_data = generate_random_bytes(sample_size)
    total_bytes += len(random_data)
    
    # Count set bits
    for byte in random_data:
        total_bits += bin(byte).count('1')
    
    total_bit_count = total_bytes * 8
    set_bit_ratio = total_bits / total_bit_count
    
    print(f"  Total bits: {total_bit_count}")
    print(f"  Set bits: {total_bits}")
    print(f"  Set bit ratio: {set_bit_ratio:.3f} (ideal: 0.5)")
    
    # Should be close to 50%
    assert 0.45 <= set_bit_ratio <= 0.55, f"Poor entropy: set bit ratio = {set_bit_ratio}"

def test_nist_preparation():
    print("Generating test data for NIST statistical tests...")
    
    total_size = 10_000_000  # 10 MB
    output_file = 'nist_test_data.bin'
    
    with open(output_file, 'wb') as f:
        bytes_written = 0
        chunk_size = 4096
        
        while bytes_written < total_size:
            remaining = total_size - bytes_written
            current_chunk_size = min(chunk_size, remaining)
            
            random_chunk = generate_random_bytes(current_chunk_size)
            f.write(random_chunk)
            bytes_written += len(random_chunk)
            
            if bytes_written % (total_size // 10) == 0:
                progress = (bytes_written / total_size) * 100
                print(f"  Progress: {progress:.0f}%")
    
    print(f"✓ Generated {bytes_written} bytes for NIST testing in '{output_file}'")

def test_error_handling():
    print("Testing error handling...")
    
    try:
        generate_random_bytes(0)
        assert False, "Should have raised ValueError for 0 bytes"
    except ValueError:
        print("Correctly handled 0 bytes request")
    
    try:
        generate_random_bytes(-1)
        assert False, "Should have raised ValueError for negative bytes"
    except ValueError:
        print("Correctly handled negative bytes request")
    
    print("✓ All error handling tests passed")

if __name__ == "__main__":
    print("Running CSPRNG Test Suite")
    print("=" * 50)
    
    try:
        test_key_uniqueness()
        print()
        
        test_entropy()
        print()
        
        test_error_handling()
        print()
        
        print(" All CSPRNG tests passed!")
        
    except Exception as e:
        print(f" Test failed: {e}")
        sys.exit(1)